package de.vwsoft.barcodelib4j;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class AutoGeneratedErr0 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test01() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test01");
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint symbolShapeHint1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint.FORCE_SQUARE;
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo2 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup(0, symbolShapeHint1);
    }

    @Test
    public void test02() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test02");
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint symbolShapeHint1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint.FORCE_SQUARE;
        de.vwsoft.barcodelib4j.twod.datamatrix.Dimension dimension4 = new de.vwsoft.barcodelib4j.twod.datamatrix.Dimension(0, 0);
        de.vwsoft.barcodelib4j.twod.zxing.common.GenericGF genericGF5 = de.vwsoft.barcodelib4j.twod.zxing.common.GenericGF.DATA_MATRIX_FIELD_256;
        java.lang.String str6 = genericGF5.toString();
        java.lang.String str7 = genericGF5.toString();
        boolean boolean8 = dimension4.equals((java.lang.Object) genericGF5);
        de.vwsoft.barcodelib4j.twod.datamatrix.Dimension dimension11 = new de.vwsoft.barcodelib4j.twod.datamatrix.Dimension(9, 21);
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo12 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup((-1), symbolShapeHint1, dimension4, dimension11, boolean8);
    }

    @Test
    public void test03() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test03");
        de.vwsoft.barcodelib4j.twod.TwoDType twoDType0 = de.vwsoft.barcodelib4j.twod.TwoDType.DATAMATRIX;
        int int1 = twoDType0.getDefaultQuietZone();
        de.vwsoft.barcodelib4j.twod.TwoDCode twoDCode2 = new de.vwsoft.barcodelib4j.twod.TwoDCode(twoDType0);
        de.vwsoft.barcodelib4j.twod.QRCodeErrorCorrection qRCodeErrorCorrection3 = de.vwsoft.barcodelib4j.twod.QRCodeErrorCorrection.H;
        java.lang.String str4 = qRCodeErrorCorrection3.getDescription();
        twoDCode2.setQRCodeErrCorr(qRCodeErrorCorrection3);
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.TwoDSymbol twoDSymbol6 = twoDCode2.buildSymbol();
    }

    @Test
    public void test04() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test04");
        de.vwsoft.barcodelib4j.image.BarExporter barExporter2 = new de.vwsoft.barcodelib4j.image.BarExporter((double) 10.0f, (double) 'a');
        barExporter2.setTiffResolution(0);
        de.vwsoft.barcodelib4j.image.CompoundColor compoundColor6 = de.vwsoft.barcodelib4j.image.CompoundColor.CC_WHITE;
        java.awt.Color color7 = java.awt.Color.getColor("GF(0x12d,256)", (java.awt.Color) compoundColor6);
        barExporter2.setBackground(compoundColor6);
        java.lang.Object obj9 = null;
        boolean boolean10 = compoundColor6.equals(obj9);
        java.awt.Color color11 = compoundColor6.brighter();
        java.awt.Color color12 = color11.brighter();
        // This assertion (symmetry of equals) fails
        org.junit.Assert.assertTrue("Contract failed: equals-symmetric on compoundColor6 and color11.", compoundColor6.equals(color11) == color11.equals(compoundColor6));
    }

    @Test
    public void test05() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test05");
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup(110);
    }

    @Test
    public void test06() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test06");
        java.awt.Color color0 = java.awt.Color.cyan;
        de.vwsoft.barcodelib4j.image.CompoundColor compoundColor1 = new de.vwsoft.barcodelib4j.image.CompoundColor(color0);
        de.vwsoft.barcodelib4j.image.CompoundColor compoundColor2 = new de.vwsoft.barcodelib4j.image.CompoundColor(color0);
        // This assertion (symmetry of equals) fails
        org.junit.Assert.assertTrue("Contract failed: equals-symmetric on color0 and compoundColor1.", color0.equals(compoundColor1) == compoundColor1.equals(color0));
    }

    @Test
    public void test07() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test07");
        de.vwsoft.barcodelib4j.image.BarExporter barExporter2 = new de.vwsoft.barcodelib4j.image.BarExporter((double) 10.0f, (double) 'a');
        barExporter2.setTiffResolution(0);
        de.vwsoft.barcodelib4j.image.CompoundColor compoundColor6 = de.vwsoft.barcodelib4j.image.CompoundColor.CC_WHITE;
        java.awt.Color color7 = java.awt.Color.getColor("GF(0x12d,256)", (java.awt.Color) compoundColor6);
        barExporter2.setBackground(compoundColor6);
        java.lang.Object obj9 = null;
        boolean boolean10 = compoundColor6.equals(obj9);
        java.awt.Color color11 = compoundColor6.brighter();
        int int12 = compoundColor6.getCMYK();
        // This assertion (symmetry of equals) fails
        org.junit.Assert.assertTrue("Contract failed: equals-symmetric on compoundColor6 and color11.", compoundColor6.equals(color11) == color11.equals(compoundColor6));
    }

    @Test
    public void test08() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test08");
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint symbolShapeHint1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolShapeHint.FORCE_RECTANGLE;
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo2 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup(1, symbolShapeHint1);
    }

    @Test
    public void test09() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test09");
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup(29);
    }

    @Test
    public void test10() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "AutoGeneratedErr0.test10");
        // during test generation this statement threw an exception of type java.lang.NullPointerException in error
        de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo symbolInfo1 = de.vwsoft.barcodelib4j.twod.datamatrix.SymbolInfo.lookup(205);
    }
}

