package de.vwsoft.barcodelib4j;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({ AutoGeneratedErr0.class })
public class AutoGeneratedErr {
}

