#!/bin/bash

mvn clean compile

find target/classes -name "*.class" ! -name "module-info.class" \
    | sed 's#target/classes/##' \
    | sed 's/\.class$//' \
    | tr '/' '.' \
    > classes.txt

CP_DEPENDENCIES=$(mvn dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q \
                 | grep -v '\[INFO\]' | tr -d '\n')

java -cp "randoop-all-4.3.4.jar:target/classes:$CP_DEPENDENCIES" \
     randoop.main.Main gentests \
     --classlist=classes.txt \
     --time-limit=600 \
     --output-limit=1000 \
     --maxsize=200 \
     --null-ratio=0.1 \
     --alias-ratio=0.2 \
     --junit-output-dir=src/test/java \
     --regression-test-basename=AutoGeneratedReg \
     --error-test-basename=AutoGeneratedErr \
     --check-compilable=true

mvn clean test-compile

mvn surefire-report:report

allure serve target/allure-results
